In [111]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [112]:
test_data=pd.read_csv('test.csv')
train_data=pd.read_csv('train.csv')

In [113]:
X=train_data[['cust_age', 'job_title', 'marital_status', 'education',
       'has_default_loan', 'cust_balance', 'has_mortgage_loan',
       'has_personal_loan', 'contact_channel', 'contact_day', 'contact_month',
       'contact_duration', 'campaign', 'pdays', 'previous_contacts',
       'previous_outcome']]
y=train_data['is_subscribed']

In [114]:
train_data

customer_id cust_age    job_title marital_status          education  \
0            11218     48.0  blue-collar         single                NaN   
1            30655     60.0    pensioner        married          secondary   
2            24190     34.0  blue-collar        married          secondary   
3            26270     50.0      manager        married  university-degree   
4            20989     60.0      manager        married  university-degree   
...            ...      ...          ...            ...                ...   
31642        13734     26.0  blue-collar         single            primary   
31643        49179     38.0      manager         single  university-degree   
31644        49350     29.0      manager         single  university-degree   
31645        38104     40.0   site-admin       divorced          secondary   
31646        28193     27.0      servant         single          secondary   

      has_default_loan cust_balance has_mortgage_loan has_personal_loan  \
0                   no         71.0               yes                no   
1                   no        781.0               yes               yes   
2                   no        157.0               yes                no   
3                   no         29.0                no               yes   
4                   no       3301.0                no                no   
...                ...          ...               ...               ...   
31642               no        102.0               yes                no   
31643               no       2368.0               yes                no   
31644               no        722.0               yes                no   
31645               no        399.0                no                no   
31646              yes       -319.0                no               yes   

      contact_channel  contact_day contact_month  contact_duration  campaign  \
0                 NaN            8           may               101         2   
1      social-network           12           aug               128         5   
2      social-network           11           jul               254         2   
3                 NaN           23           jul               104         1   
4                 NaN           17           jun              2621         3   
...               ...          ...           ...               ...       ...   
31642             NaN           16           may                46         1   
31643  social-network           18           may               241         3   
31644       telephone           18           may                81         4   
31645  social-network           28           jan               246         2   
31646  social-network           30           jul                89         2   

       pdays  previous_contacts previous_outcome  is_subscribed  
0         -1                  0              NaN          False  
1         -1                  0              NaN          False  
2         -1                  0              NaN          False  
3         -1                  0              NaN          False  
4         -1                  0              NaN           True  
...      ...                ...              ...            ...  
31642     -1                  0              NaN          False  
31643     -1                  0              NaN          False  
31644     -1                  0              NaN          False  
31645     -1                  0              NaN          False  
31646     -1                  0              NaN          False  

[31647 rows x 18 columns]

In [115]:
train_data.dtypes

customer_id           int64
cust_age             object
job_title            object
marital_status       object
education            object
has_default_loan     object
cust_balance         object
has_mortgage_loan    object
has_personal_loan    object
contact_channel      object
contact_day           int64
contact_month        object
contact_duration      int64
campaign              int64
pdays                 int64
previous_contacts     int64
previous_outcome     object
is_subscribed          bool
dtype: object

In [116]:
X[['cust_age','cust_balance']] = X[['cust_age','cust_balance']].astype(str)


/home/aliyusifov/miniconda3/envs/main/lib/python3.9/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


In [117]:
X['cust_age'] = X['cust_age'].map(lambda x: x.rstrip('/r').rstrip('/'))
X['cust_balance']= X['cust_balance'].map(lambda x: x.rstrip('/r').lstrip('/'))



<ipython-input-117-0ede77350349>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['cust_age'] = X['cust_age'].map(lambda x: x.rstrip('/r').rstrip('/'))
<ipython-input-117-0ede77350349>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['cust_balance']= X['cust_balance'].map(lambda x: x.rstrip('/r').lstrip('/'))


In [118]:
#converting cust_age and cust_balance columns to float
X["cust_age"] = pd.to_numeric(X["cust_age"], errors='coerce')
X["cust_balance"] = pd.to_numeric(X["cust_balance"], errors='coerce')



<ipython-input-118-37f7b1898fc7>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["cust_age"] = pd.to_numeric(X["cust_age"], errors='coerce')
<ipython-input-118-37f7b1898fc7>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["cust_balance"] = pd.to_numeric(X["cust_balance"], errors='coerce')


Preprocessing data

In [119]:
#Checking null valeus
X.isnull().sum()

cust_age               344
job_title              204
marital_status           0
education             1325
has_default_loan         0
cust_balance           440
has_mortgage_loan        0
has_personal_loan        0
contact_channel       9151
contact_day              0
contact_month            0
contact_duration         0
campaign                 0
pdays                    0
previous_contacts        0
previous_outcome     25889
dtype: int64

In [120]:
X.columns

Index(['cust_age', 'job_title', 'marital_status', 'education',
       'has_default_loan', 'cust_balance', 'has_mortgage_loan',
       'has_personal_loan', 'contact_channel', 'contact_day', 'contact_month',
       'contact_duration', 'campaign', 'pdays', 'previous_contacts',
       'previous_outcome'],
      dtype='object')

In [121]:
#imputatio for numerical values
from sklearn.impute import SimpleImputer
num_imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
X[['cust_age','cust_balance']]=num_imputer.fit_transform(X[['cust_age','cust_balance']])

<ipython-input-121-faf443ae5815>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[['cust_age','cust_balance']]=num_imputer.fit_transform(X[['cust_age','cust_balance']])
/home/aliyusifov/miniconda3/envs/main/lib/python3.9/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)


In [122]:
X.isnull().sum()


cust_age                 0
job_title              204
marital_status           0
education             1325
has_default_loan         0
cust_balance             0
has_mortgage_loan        0
has_personal_loan        0
contact_channel       9151
contact_day              0
contact_month            0
contact_duration         0
campaign                 0
pdays                    0
previous_contacts        0
previous_outcome     25889
dtype: int64

In [123]:
cat_imputer=SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X[['job_title', 'education', 'contact_channel', 'previous_outcome']]=cat_imputer.fit_transform(X[['job_title', 'education', 'contact_channel', 'previous_outcome']])

<ipython-input-123-b27e7daea21f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[['job_title', 'education', 'contact_channel', 'previous_outcome']]=cat_imputer.fit_transform(X[['job_title', 'education', 'contact_channel', 'previous_outcome']])
/home/aliyusifov/miniconda3/envs/main/lib/python3.9/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)


In [124]:
X.isnull().sum()

cust_age             0
job_title            0
marital_status       0
education            0
has_default_loan     0
cust_balance         0
has_mortgage_loan    0
has_personal_loan    0
contact_channel      0
contact_day          0
contact_month        0
contact_duration     0
campaign             0
pdays                0
previous_contacts    0
previous_outcome     0
dtype: int64

In [125]:
#encoding independent values
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
X['job_title']=encoder.fit_transform(X['job_title'])
X['marital_status']=encoder.fit_transform(X['marital_status'])
X['education']=encoder.fit_transform(X['education'])
X['has_default_loan']=encoder.fit_transform(X['has_default_loan'])
X['has_mortgage_loan']=encoder.fit_transform(X['has_mortgage_loan'])
X['has_personal_loan']=encoder.fit_transform(X['has_personal_loan'])
X['contact_channel']=encoder.fit_transform(X['contact_channel'])
X['contact_month']=encoder.fit_transform(X['contact_month'])
X['previous_outcome']=encoder.fit_transform(X['previous_outcome'])

<ipython-input-125-1be032bebeb7>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['job_title']=encoder.fit_transform(X['job_title'])
<ipython-input-125-1be032bebeb7>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['marital_status']=encoder.fit_transform(X['marital_status'])
<ipython-input-125-1be032bebeb7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://p

In [126]:
X

cust_age  job_title  marital_status  education  has_default_loan  \
0          48.0          0               2          1                 0   
1          60.0          6               1          1                 0   
2          34.0          0               1          1                 0   
3          50.0          4               1          2                 0   
4          60.0          4               1          2                 0   
...         ...        ...             ...        ...               ...   
31642      26.0          0               2          0                 0   
31643      38.0          4               2          2                 0   
31644      29.0          4               2          2                 0   
31645      40.0          9               0          1                 0   
31646      27.0          8               2          1                 1   

       cust_balance  has_mortgage_loan  has_personal_loan  contact_channel  \
0              71.0                  1                  0                1   
1             781.0                  1                  1                1   
2             157.0                  1                  0                1   
3              29.0                  0                  1                1   
4            3301.0                  0                  0                1   
...             ...                ...                ...              ...   
31642         102.0                  1                  0                1   
31643        2368.0                  1                  0                1   
31644         722.0                  1                  0                4   
31645         399.0                  0                  0                1   
31646        -319.0                  0                  1                1   

       contact_day  contact_month  contact_duration  campaign  pdays  \
0                8              8               101         2     -1   
1               12              1               128         5     -1   
2               11              5               254         2     -1   
3               23              5               104         1     -1   
4               17              6              2621         3     -1   
...            ...            ...               ...       ...    ...   
31642           16              8                46         1     -1   
31643           18              8               241         3     -1   
31644           18              8                81         4     -1   
31645           28              4               246         2     -1   
31646           30              5                89         2     -1   

       previous_contacts  previous_outcome  
0                      0                 0  
1                      0                 0  
2                      0                 0  
3                      0                 0  
4                      0                 0  
...                  ...               ...  
31642                  0                 0  
31643                  0                 0  
31644                  0                 0  
31645                  0                 0  
31646                  0                 0  

[31647 rows x 16 columns]

In [127]:
#encoding dependent variable
encode=LabelEncoder()
y=encoder.fit_transform(y)

In [128]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [129]:
#splitting train and test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.25, random_state=1234)


In [130]:
#checking models

In [131]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
log_reg_class=LogisticRegression()
log_reg_class.fit(X_train, y_train)


/home/aliyusifov/miniconda3/envs/main/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [132]:
y_pred=log_reg_class.predict(X_test)

In [133]:
from sklearn.metrics import accuracy_score,confusion_matrix, f1_score
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'F1 score: {f1_score(y_test, y_pred)}')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8856167846309403
F1 score: 0.2672064777327935
[[6842  130]
 [ 775  165]]


In [134]:
#Naive Bayes 
from sklearn.naive_bayes import GaussianNB
nb_class=GaussianNB()
nb_class.fit(X_train, y_train)

GaussianNB()

In [135]:
y_pred=nb_class.predict(X_test)

In [136]:
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'F1 score: {f1_score(y_test, y_pred)}')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8610970677451971
F1 score: 0.44466902475997977
[[6373  599]
 [ 500  440]]


In [137]:
#KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
knn_class=KNeighborsClassifier()
knn_class.fit(X_train, y_train)

KNeighborsClassifier()

In [138]:
y_pred=knn_class.predict(X_test)

In [139]:
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'F1 score: {f1_score(y_test, y_pred)}')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8828361981799798
F1 score: 0.3689584751531655
[[6714  258]
 [ 669  271]]


In [140]:
#DecisionTreeCLassifier
from sklearn.tree import DecisionTreeClassifier
tree_class=DecisionTreeClassifier()
tree_class.fit(X_train, y_train)

DecisionTreeClassifier()

In [141]:
y_pred=tree_class.predict(X_test)

In [142]:
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'F1 score: {f1_score(y_test, y_pred)}')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8693124368048534
F1 score: 0.45058448459086076
[[6454  518]
 [ 516  424]]


In [143]:
#RandomForest
from sklearn.ensemble import RandomForestClassifier
rf_class=RandomForestClassifier(n_estimators=100)
rf_class.fit(X_train, y_train)

RandomForestClassifier()

In [144]:
y_pred=rf_class.predict(X_test)

In [145]:
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'F1 score: {f1_score(y_test, y_pred)}')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9053336703741153
F1 score: 0.4976525821596244
[[6792  180]
 [ 569  371]]


In [146]:
#XGboosting
from xgboost import XGBClassifier
xgb_class=XGBClassifier()
xgb_class.fit(X_train, y_train)

[22:27:03] WARNING: /tmp/build/80754af9/xgboost-split_1619724447847/work/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
/home/aliyusifov/miniconda3/envs/main/lib/python3.9/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [147]:
y_pred=xgb_class.predict(X_test)

In [148]:
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'F1 score: {f1_score(y_test, y_pred)}')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.904196157735086
F1 score: 0.5190355329949239
[[6745  227]
 [ 531  409]]


In [149]:
#Applying on Test data

In [150]:
X=test_data[['cust_age', 'job_title', 'marital_status', 'education',
       'has_default_loan', 'cust_balance', 'has_mortgage_loan',
       'has_personal_loan', 'contact_channel', 'contact_day', 'contact_month',
       'contact_duration', 'campaign', 'pdays', 'previous_contacts',
       'previous_outcome']]

In [151]:
test_data.dtypes

customer_id           int64
cust_age             object
job_title            object
marital_status       object
education            object
has_default_loan     object
cust_balance         object
has_mortgage_loan    object
has_personal_loan    object
contact_channel      object
contact_day           int64
contact_month        object
contact_duration      int64
campaign              int64
pdays                 int64
previous_contacts     int64
previous_outcome     object
dtype: object

In [152]:
X[['cust_age','cust_balance']] = X[['cust_age','cust_balance']].astype(str)

/home/aliyusifov/miniconda3/envs/main/lib/python3.9/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


In [153]:
X['cust_age'] = X['cust_age'].map(lambda x: x.rstrip('/r').rstrip('/'))
X['cust_balance']= X['cust_balance'].map(lambda x: x.rstrip('/r').lstrip('/'))

<ipython-input-153-915905bf422e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['cust_age'] = X['cust_age'].map(lambda x: x.rstrip('/r').rstrip('/'))
<ipython-input-153-915905bf422e>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['cust_balance']= X['cust_balance'].map(lambda x: x.rstrip('/r').lstrip('/'))


In [154]:
#converting cust_age and cust_balance columns to float
X["cust_age"] = pd.to_numeric(X["cust_age"], errors='coerce')
X["cust_balance"] = pd.to_numeric(X["cust_balance"], errors='coerce')

<ipython-input-154-4c2ea8c35aae>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["cust_age"] = pd.to_numeric(X["cust_age"], errors='coerce')
<ipython-input-154-4c2ea8c35aae>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["cust_balance"] = pd.to_numeric(X["cust_balance"], errors='coerce')


In [155]:
X.isnull().sum()

cust_age               155
job_title               84
marital_status           0
education              532
has_default_loan         0
cust_balance           185
has_mortgage_loan        0
has_personal_loan        0
contact_channel       3869
contact_day              0
contact_month            0
contact_duration         0
campaign                 0
pdays                    0
previous_contacts        0
previous_outcome     11070
dtype: int64

In [156]:
#imputatio for numerical values
num_imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
X[['cust_age','cust_balance']]=num_imputer.fit_transform(X[['cust_age','cust_balance']])

<ipython-input-156-f60f1c2a3663>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[['cust_age','cust_balance']]=num_imputer.fit_transform(X[['cust_age','cust_balance']])
/home/aliyusifov/miniconda3/envs/main/lib/python3.9/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)


In [157]:
cat_imputer=SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X[['job_title', 'education', 'contact_channel', 'previous_outcome']]=cat_imputer.fit_transform(X[['job_title', 'education', 'contact_channel', 'previous_outcome']])

<ipython-input-157-b27e7daea21f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[['job_title', 'education', 'contact_channel', 'previous_outcome']]=cat_imputer.fit_transform(X[['job_title', 'education', 'contact_channel', 'previous_outcome']])
/home/aliyusifov/miniconda3/envs/main/lib/python3.9/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)


In [158]:
X.isnull().sum()

cust_age             0
job_title            0
marital_status       0
education            0
has_default_loan     0
cust_balance         0
has_mortgage_loan    0
has_personal_loan    0
contact_channel      0
contact_day          0
contact_month        0
contact_duration     0
campaign             0
pdays                0
previous_contacts    0
previous_outcome     0
dtype: int64

In [159]:
#encoding independent values
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
X['job_title']=encoder.fit_transform(X['job_title'])
X['marital_status']=encoder.fit_transform(X['marital_status'])
X['education']=encoder.fit_transform(X['education'])
X['has_default_loan']=encoder.fit_transform(X['has_default_loan'])
X['has_mortgage_loan']=encoder.fit_transform(X['has_mortgage_loan'])
X['has_personal_loan']=encoder.fit_transform(X['has_personal_loan'])
X['contact_channel']=encoder.fit_transform(X['contact_channel'])
X['contact_month']=encoder.fit_transform(X['contact_month'])
X['previous_outcome']=encoder.fit_transform(X['previous_outcome'])

<ipython-input-159-1be032bebeb7>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['job_title']=encoder.fit_transform(X['job_title'])
<ipython-input-159-1be032bebeb7>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['marital_status']=encoder.fit_transform(X['marital_status'])
<ipython-input-159-1be032bebeb7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://p

In [160]:
X

cust_age  job_title  marital_status  education  has_default_loan  \
0      58.000000          0               1          0                 0   
1      40.904691          4               1          2                 0   
2      33.000000          4               1          2                 0   
3      36.000000          4               1          2                 0   
4      55.000000          1               1          1                 0   
...          ...        ...             ...        ...               ...   
13559  35.000000          1               2          2                 0   
13560  37.000000          9               2          1                 0   
13561  37.000000         13               1          1                 0   
13562  34.000000          9               1          1                 0   
13563  51.000000          4               1          2                 0   

       cust_balance  has_mortgage_loan  has_personal_loan  contact_channel  \
0            1231.0                  0                  0                1   
1               0.0                  0                  0                1   
2            2173.0                  1                  0                1   
3             502.0                  1                  0                1   
4               0.0                  1                  0                1   
...             ...                ...                ...              ...   
13559        1924.0                  1                  0                1   
13560           0.0                  0                  0                1   
13561          80.0                  0                  0                1   
13562        -312.0                  1                  0                1   
13563         469.0                  0                  0                1   

       contact_day  contact_month  contact_duration  campaign  pdays  \
0               20              6                21         3     -1   
1               14              1                64         2     -1   
2               15              0               871         1     -1   
3               21              8               509         1     -1   
4               16              8               248         3     -1   
...            ...            ...               ...       ...    ...   
13559           20              0               285         1     -1   
13560           21              9               232         2     -1   
13561            3              3               248         2     -1   
13562            9              8               232         1     -1   
13563           15              0               200         1    181   

       previous_contacts  previous_outcome  
0                      0                 0  
1                      0                 0  
2                      0                 0  
3                      0                 0  
4                      0                 0  
...                  ...               ...  
13559                  0                 0  
13560                  0                 0  
13561                  0                 0  
13562                  0                 0  
13563                  2                 2  

[13564 rows x 16 columns]

In [161]:
y_pred=xgb_class.predict(X)

In [162]:
y_pred

array([0, 0, 1, ..., 0, 0, 1])

In [163]:
print(y_pred)

[0 0 1 ... 0 0 1]


In [164]:
y_pred=pd.DataFrame(y_pred, columns=['is_subscribed'])

In [165]:
y_pred

is_subscribed
0                  0
1                  0
2                  1
3                  0
4                  0
...              ...
13559              0
13560              0
13561              0
13562              0
13563              1

[13564 rows x 1 columns]

In [166]:
y_pred=y_pred.replace((1, 0), ('TRUE', 'FALSE'))

In [167]:
y_pred

is_subscribed
0             FALSE
1             FALSE
2              TRUE
3             FALSE
4             FALSE
...             ...
13559         FALSE
13560         FALSE
13561         FALSE
13562         FALSE
13563          TRUE

[13564 rows x 1 columns]

In [168]:
id=test_data['customer_id']

In [169]:
id

0        22154
1        31186
2        42151
3        14944
4        13657
         ...  
13559    43181
13560    37261
13561    39647
13562    11882
13563    53479
Name: customer_id, Length: 13564, dtype: int64

In [172]:
final_df=pd.concat([id, y_pred],axis=1)

In [173]:
final_df

customer_id is_subscribed
0            22154         FALSE
1            31186         FALSE
2            42151          TRUE
3            14944         FALSE
4            13657         FALSE
...            ...           ...
13559        43181         FALSE
13560        37261         FALSE
13561        39647         FALSE
13562        11882         FALSE
13563        53479          TRUE

[13564 rows x 2 columns]

In [174]:
final_df.to_csv('sample_warriors.csv', index=False)